### ISSUE TITLE
Error at 2.2 - ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by mrmds** [jeremySrgt/mini-modern-data-stack#1]
Hi Jeremy

Thanks very much for this project - As a non-developer trying to build my first webapp this is an amazing leg up for my understanding.

I am unfortunately getting an error at the Pulumi implementation stage when both previewing and implementing - ModuleNotFoundError: No module named 'pkg_resources'.

_Diagnostics:
  pulumi:pulumi:Stack (mini-data-stack-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/**/Documents/mini-modern-data-stack/stack/pulumi/__main__.py", line 3, in <module>
        import jobs.ecr as ecr
      File "/Users/**/Documents/mini-modern-data-stack/stack/pulumi/jobs/ecr.py", line 3, in <module>
        import pulumi_awsx as awsx
      File "/Users/**/Documents/mini-modern-data-stack/data_stack_venv/lib/python3.12/site-packages/pulumi_awsx/__init__.py", line 5, in <module>
        from . import _utilities
      File "/Users/**/Documents/mini-modern-data-stack/data_stack_venv/lib/python3.12/site-packages/pulumi_awsx/_utilities.py", line 10, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'_

I would love to continue this implementation and any thoughts you have would be appreciated.

Matt

**Comment by jeremySrgt** [comment]
Hello 

I think it's a bug on pulumi package dependency

You will need to manually install setuptools in the python env you are using

`pip install setuptools`

Hope it works !

**Comment by mrmds** [comment]
Hi Jeremy, this worked well thanks! Unfortunately it led to the next issue when running both ansible playbooks:

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Could not match supplied host pattern, ignoring: group_airbyte_instance

PLAY [group_airbyte_instance] ************************************************************************************************************************************
skipping: no hosts matched

Looking on stackoverflow etc many answers go to no directory for hosts but tried adding one without success.
Sorry to be a bother - I'm open to any thoughts you have.

Thanks in advance!
Matt

**Comment by jeremySrgt** [comment]
Do you have the instances running on AWS ?
